apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentkitmarket.fullname" . }}-api
  labels:
    {{- include "agentkitmarket.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "agentkitmarket.selectorLabelsApi" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
